### Perform aggregation
POST http://localhost:3000/aggregate
Content-Type: application/json
x-api-key: aYsTVw%p5HgUz4n8Wijm

{
  "collection": "users",
  "pipeline": [
    {
      "$match": {
        "age": {
          "$gt": 20
        }
      }
    },
    {
      "$group": {
        "_id": "$age",
        "count": {
          "$sum": 1
        }
      }
    }
  ]
}
