### Delete documents
DELETE http://localhost:3000/delete
Content-Type: application/json
x-api-key: aYsTVw%p5HgUz4n8Wijm

{
  "collection": "users",
  "query": {
    "email": "jane.doe@example.com"
  }
}
